-- Changelog: shown in Settings > CHANGELOG. Newest first. Keep items short (one line each).
return {
	{
		version = "Alpha 0.3",
		date = "2 Oct 2026",
		items = {
			"OFFICERS: hire unique officers in 8 rarities (Common to Forbidden), each with its own traits, and equip them with weapons and armor",
			"You are an officer too: your leader slot sits on top and wears gear",
			"CRATES: Supply Crate (cash) and the limited Founder's Crate (gold or Robux), with a new reveal animation",
			"INVENTORY: every weapon, armor piece, crate and benched officer in one place",
			"RAIDS: attack players in your server and 3 AI nations that raid back; take 10% of their cash on hand",
			"REVENGE: when someone raids you, strike back in one tap",
			"THE BANK: deposit cash (10% fee) to keep it safe from raids and earn 1.5% interest per hour",
			"ALLIANCES: leaders can set a join fee and dues (flat, progressive or regressive)",
			"ORDERS: 5 daily orders from a pool of 20 plus 5 weekly challenges, all paying SEALS; one free replace a day",
			"SEALS SHOP: trade Seals for Takedown tickets, refills, raid shields and crates",
			"DAILY LOGIN SHEET: 7 rewards that pause instead of reset; day 7 gives gold and a Founder's Crate",
			"ALLIANCE WEEKLY TAKEDOWN: 5 stages against a weekly stronghold, with free attacks, tickets and a damage leaderboard",
			"LAW MASTERY: Bronze, Silver and Gold medals for every law; Gold gives a skill point",
			"CONVOYS: pay now depends on trading between different regions, and city wants change as players deliver",
			"VIP and MEGA VIP passes with chat tags; Mega VIP includes a limited officer",
			"New painted art everywhere: country scenes, buildings, gear, officers, crates and enemies",
			"RAID FIGHTS: watch three rounds of blows with crits, weapons (or fists) and impact effects",
			"SPIES: other nations' stats are hidden until you spy on them (they will know)",
			"RENT: alliances holding a capital can charge its residents rent; new players are exempt for 48 hours",
			"GLOBAL CITIES: New York, Los Angeles, London, Tokyo, Paris and Shanghai are the richest prizes",
			"LIVING CITY: buildings glow and flicker, construction plays out on the lot",
			"The world map now loops around the globe",
			"Sound effects and music",
			"Settings, a visual Game Guide and this changelog (top-right gear)",
		},
	},
	{
		version = "Alpha 0.2",
		date = "1 Oct 2026",
		items = {
			"THE WORLD MAP: the Capitol map is now the home screen",
			"Convoys travel between real world capitals and deliver the goods each city wants",
			"Alliances can capture and hold cities on the map",
			"City taxes: alliances that hold a city tax the trade passing through it",
			"Onboarding: name your country, design your flag, pick an ideology and a home capital",
		},
	},
	{
		version = "Alpha 0.1",
		date = "26 Sep 2026",
		items = {
			"First prototype of Idle Country",
			"Laws: pass laws with Influence to earn cash and XP",
			"Properties: build income buildings on your lots",
			"Military: recruit an army to attack and defend",
			"Bosses: defeat bosses with Supply for gold",
			"Alliances: team up with other players",
		},
	},
}
