-- Changelog: shown in Settings > CHANGELOG. Newest first. Keep items short (one line each).
return {
	{
		version = "Alpha 0.4",
		date = "3 Oct 2026",
		items = {
			"ERAS: advance through 8 eras from LAWS once you reach each era's level",
			"WONDERS: build your nation's Wonder from the Classical era; every stage adds +2% property income forever",
			"GOVERNMENT: pick Democracy, Monarchy, Federation, Military Junta, Theocracy or Technocracy when you found your country, each with its own bonus",
			"WORLD EVENTS: game-wide events in every server; send a convoy to the event city for 2.5x pay",
			"City demand is now shared by every server",
			"GEAR SHOP: new weapons and armor every 5 minutes, rarer gear at higher levels",
			"PITY: a Legendary or better is guaranteed within 30 Founder's Crates or 50 Supply Crates, with a progress bar on each crate",
			"AFK CHAMBER: stay in the game while idle, keep earning and find rare items",
			"BUY CONVOYS: new convoys are bought with cash as you level up",
			"TUTORIAL: an optional guided tour for new players, with highlighted buttons",
			"Tabs now unlock as you level up; Shop, Military and Raids open at level 3",
			"Leveling is smoother in the first levels",
			"PROFILES: tap a nation to see its profile, titles and achievements",
			"BADGES: earn badges for big milestones",
			"FREE GIFT: like the game and join the group for 100 gold and a Founder's Crate",
			"New passes: 2x Influence Regen and 2x Supply Regen",
			"Gold packs give bonus gold on the bigger packs; gold prices match Robux 1:1",
			"STARTER PACK for new players",
			"Owned passes show OWNED in the shop",
			"Volume sliders for music and sound effects, and new sounds for rare finds",
			"Global chat: type /g to talk to every server",
			"Better layout on phones",
			"The Game Guide now explains gold bars, eras, government, bosses, alliances and more",
			"Removed: Takedown tickets and the Alliance Weekly Takedown",
		},
	},
	{
		version = "Alpha 0.3",
		date = "2 Oct 2026",
		items = {
			"OFFICERS: hire unique officers in 8 rarities (Common to Forbidden), each with its own traits, and equip them with weapons and armor",
			"You are an officer too: your leader slot sits on top and wears gear",
			"CRATES: Supply Crate (cash) and the limited Founder's Crate (gold or Robux), with a new reveal animation",
			"INVENTORY: every weapon, armor piece, crate and benched officer in one place",
			"RAIDS: attack players in your server and 3 AI nations that raid back; take 10% of their cash on hand",
			"REVENGE: when someone raids you, strike back in one tap",
			"THE BANK: deposit cash (10% fee) to keep it safe from raids and earn 1.5% interest per hour",
			"ALLIANCES: leaders can set a join fee and dues",
			"ORDERS: daily orders and weekly challenges that pay MERITS",
			"MERITS SHOP: trade Merits for Takedown tickets, refills, raid shields and crates",
			"DAILY LOGIN: come back every day for a reward; day 7 gives gold and a Founder's Crate",
			"ALLIANCE WEEKLY TAKEDOWN: 5 stages against a weekly stronghold, with free attacks, tickets and a damage leaderboard",
			"LAW MASTERY: Bronze, Silver and Gold medals for every law; Gold gives a skill point",
			"CONVOYS: trade between different regions for bigger pay",
			"VIP and MEGA VIP passes with chat tags; Mega VIP includes a limited officer",
			"New painted art everywhere: country scenes, buildings, gear, officers, crates and enemies",
			"RAID FIGHTS: watch three rounds of blows with crits, weapons (or fists) and impact effects",
			"SPIES: spy on other nations to see their stats",
			"RENT: alliances holding a capital can charge its residents rent",
			"GLOBAL CITIES: New York, Los Angeles, London, Tokyo, Paris and Shanghai are the richest prizes",
			"LIVING CITY: buildings glow and flicker, construction plays out on the lot",
			"The world map now loops around the globe",
			"Sound effects and music",
			"Settings, a visual Game Guide and this changelog (top-right gear)",
		},
	},
	{
		version = "Alpha 0.2",
		date = "1 Oct 2026",
		items = {
			"THE WORLD MAP: the World map is now the home screen",
			"Convoys travel between real world capitals and deliver the goods each city wants",
			"Alliances can capture and hold cities on the map",
			"City taxes: alliances that hold a city tax the trade passing through it",
			"Onboarding: name your country, design your flag, pick an ideology and a home capital",
		},
	},
	{
		version = "Alpha 0.1",
		date = "26 Sep 2026",
		items = {
			"First prototype of Idle Country",
			"Laws: pass laws with Influence to earn cash and XP",
			"Properties: build income buildings on your lots",
			"Military: recruit an army to attack and defend",
			"Bosses: defeat bosses with Supply for gold",
			"Alliances: team up with other players",
		},
	},
}
