import json
exec(open('/home/claude/main/art/ads/v14/prompts.py').read().split("X=[")[0])
X=[
 ("rule_noob",["v15ref_rule.jpg","sref_03.jpg"],"Same composition as the first attached image, but the emperor standing on the blue globe is a classic yellow Roblox noob (yellow head and arms, blue torso, green legs) wearing a gold crown, navy coat and red sash, planting the royal blue crown flag, grinning. He is big and fills the upper half; golden god rays and blue crown banners in a sunset sky."),
 ("rule_night",["v15ref_rule.jpg","sref_06.jpg"],"Same composition as the first attached image but at night: the Roblox bacon hair emperor in gold crown and navy coat stands big on top of a glowing royal blue globe planting the blue crown flag, moonlight and a starry deep blue sky, torches and blue crown banners around, the globe lights his face from below."),
 ("rule_title",["v15ref_rule.jpg","v14ref_rule.jpg"],"Same close composition as the first attached image (the emperor big on the globe planting the blue crown flag), and add the big title RULE THE WORLD across the top in the exact title lettering of the second attached image. Keep the ruler large."),
 ("throne_doors",["v15ref_throne.jpg","sref_14.jpg"],"Same ruler and throne as the first attached image, big in the frame, but behind the throne two giant open palace doors show his royal blue army marching in rows under gold crown banners toward a burning crimson enemy castle at sunset."),
 ("throne_advisor",["v15ref_throne.jpg","sref_02.jpg"],"Same ruler on the golden throne as the first attached image, big and grinning; in the lower right foreground a classic yellow Roblox noob general in a navy uniform kneels and holds up an unrolled map showing new land painted royal blue. Only these two characters, throne room with blue crown banners."),
 ("point_balcony",["v15ref_point.jpg","sref_14.jpg"],"Same Roblox bacon hair emperor as the first attached image, big in the frame, standing on a stone castle balcony and pointing straight at the viewer with a confident grin; behind and below him his royal blue army fills a courtyard under gold crown banners, conquered city with blue flags at sunset."),
 ("point_wartable",["v15ref_point.jpg","sref_16.jpg"],"Same Roblox bacon hair emperor as the first attached image, leaning over a war table toward the viewer and pointing straight at us, big in the frame; on the table in the foreground a parchment map where his royal blue territory has swallowed most countries, little blue crown flags, warm candlelight, blue banners behind."),
 ("europe_flag",["v15ref_naflag.jpg","sref_16.jpg"],"Same hand-inked parchment map style as the first attached image, but showing Europe zoomed in: most of Europe is royal blue and one single huge royal blue crown flag is planted in the middle of it, the biggest thing in the image; fire and smoke along the eastern border as blue spreads into crimson red lands, red white-star flags toppling. Bird's-eye, compass rose, no characters."),
 ("world_flag",["v15ref_naflag.jpg","sref_03.jpg"],"Same hand-inked parchment map style as the first attached image, showing the whole world map: almost every continent is royal blue, only small crimson red patches with white-star flags remain and are burning; one single huge royal blue crown flag stands planted in the centre of the map as the focal point. Bird's-eye, no characters."),
 ("hand_flag",["v15ref_naflag.jpg","ref_hand_v15.jpg"],"Extreme close-up: a blocky Roblox hand in a navy sleeve with gold cuff pushes a big royal blue crown flag pin into a hand-inked parchment map of North America, crimson white-star flag pins knocked over around it, gold coins and candlelight on the map table, like the hand in the second attached image. No full characters."),
 ("rival_panic",["v15ref_throne.jpg","sref_04.jpg"],"A classic yellow Roblox noob king in a crimson robe and crown, big in the frame, grabs his head in panic in front of a huge wall map where royal blue territory with gold crown flags is swallowing his crimson red land, fire glow through the window, crimson white-star banners. Only one character."),
 ("map_growth",["v15ref_naflag.jpg","sref_16.jpg"],"Split image in the hand-inked parchment map style of the first attached image: on the left the map of North America with only one tiny royal blue country and one small crown flag; on the right the same map with the whole continent royal blue, many crown flags and a huge flag in the middle. One single thick red curved arrow from left to right between them. No characters."),
]
json.dump([[r,s+CLEAN.replace("NO TEXT anywhere in the image. ","" if k=="rule_title" else "NO TEXT anywhere in the image. ")+" "+STYLE] for k,r,s in X],open('/home/claude/main/art/ads/v15/v5.json','w'))
json.dump([k for k,_,_ in X],open('/home/claude/main/art/ads/v15/keys.json','w'))
print(len(X))
