# file, title, score, status, why
C=[
("v13/rule_the_world_clean.jpg","Rule the World",84,"Kash liked","The end goal of every country game in one picture: crowned ruler on a blue globe, army below. One big subject, warm high-contrast light, 3-word title. Reads at phone size."),
("v12/r2_take_their_capital_a.jpg","Take Their Capital",77,"Kash: decent","Enemy, win and reaction in one frame (our flag up, their king running). Rivalry + capture is the top-converting pattern in country games. Real feature (capitals)."),
("v13/conquer_europe_a.jpg","Conquer the World (Europe map)",71,"New","Map conquest is the most-used hook in the genre (Pixel Conquest, Conquer The World WW2). Hand-drawn map stands out from neon maps. Small details may blur at 110px."),
("v13/conquer_namerica_a.jpg","Conquer the World (N. America)",67,"New","Same map hook, zoomed in, no arrow. US shape is instantly recognised, which helps the main English-speaking audience. Fire line shows the war."),
("v13/defeat_the_warlord_b.jpg","Defeat the Warlord",64,"New","Boss fights sell well in simulator ads (big face + health bar). Real feature. Less on-brand for 'country game' so weaker for this audience."),
("v13/conquer_europe_b.jpg","Conquer the World (Europe alt)",62,"Alternate","Cleaner map, less action at the arrow tip than the main Europe version."),
("v9/na_fight_left_a.jpg","Fight for Territory",62,"Earlier set","Proven competitor layout (title left, map clash right). Dark map is a little low-contrast on the homepage."),
("v13/raid_notext_a.jpg","Raid (no text)",58,"Kash: try no text","Steal hooks are huge on the homepage right now, and the scene reads without text. Raid is a side feature, so it may bring players expecting a stealing game."),
("v13/conquer_namerica_b.jpg","Conquer the World (N. America alt)",58,"Alternate","Good shape, but the action is smaller and the parchment is plainer."),
("v13/defeat_the_warlord_a.jpg","Defeat the Warlord (alt)",58,"Alternate","Same idea; bacon pose and pants read slightly off."),
("v8/fight_for_territory_b.jpg","Fight for Territory (bold map)",57,"Earlier set","Strong colour blocks and clash arrows; style is closer to Idle Mafia than to the house style."),
("v12/r1_conquer_the_world_b.jpg","Conquer the World (general)",55,"Kash: avatar off","Good map hook, but the avatar was rejected and the map is tilted, not bird's-eye."),
("art/ads/style_refs/style_16.jpg","FIGHT FOR TERRITORY (current)",55,"Current thumbnail","Best of the current set because it shows land being taken. Dark and small on mobile."),
("v6/biggest_empire_a.jpg","Build the Biggest Empire",53,"Earlier set","Ruler on a globe like Rule the World, but less dramatic and busier title."),
("v12/r2_alliance_war_a.jpg","Alliance War",52,"Earlier set","Two allies + army is clear, but crowds read as AI and 'alliance' is a second-tier want."),
("v8/capture_capitals_b.jpg","Capture Capitals (map)",52,"Earlier set","Clear clash on a world map; too many colours compete at small size."),
("v6/capture_capitals_a.jpg","Capture Capitals (desk)",50,"Earlier set","Indoor desk scene: shows a map, but not the act of conquering."),
("v12/r2_expand_your_borders_a.jpg","Expand Your Borders",50,"Earlier set","Map hook, but four arrows and repeated '+1 TERRITORY' clutter it."),
("v6/win_the_war_a.jpg","Win the War",49,"Earlier set","Battle scene with two avatars; crowd detail reads as AI at full size."),
("v12/r2_defend_your_nation_a.jpg","Defend Your Nation",48,"Earlier set","Defence is less exciting than attack for this audience."),
("v12/r2_from_peasant_to_king_a.jpg","Peasant to Emperor",47,"Earlier set","Before/after works in sims, but Kash found this style AI-looking and the country fantasy is weak."),
("v12/r2_raise_a_million_a.jpg","1 Soldier to 1,000,000",45,"Earlier set","Numbers hook, but tiny repeated soldiers turn to mush on mobile."),
("art/ads/style_refs/style_01.jpg","RULE YOUR NATION (current)",38,"Current thumbnail","Indoor throne room, no land or army; the type of image the research says undersells."),
]
