window.sleep=ms=>new Promise(r=>setTimeout(r,ms));
window.__flowOpenPicker=()=>[...document.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')=='Add ingredients to the prompt box').click();
window.__flowPrompt=async(text)=>{const ed=document.querySelector('[contenteditable=true]'); ed.focus(); document.execCommand('selectAll'); document.execCommand('insertText',false,text); await sleep(300); return ed.textContent.length;};
window.__uploadBlob=async(blob,name)=>{const file=new File([blob],name,{type:blob.type||'image/jpeg'}); if(!document.querySelector('button[role=option]')){__flowOpenPicker(); await sleep(1500);} const b=[...document.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')=='Upload media'); if(!b) return 'no upload button'; const orig=HTMLInputElement.prototype.click; let done=false; HTMLInputElement.prototype.click=function(){ if(this.type==='file'&&!done){done=true; const dt=new DataTransfer(); dt.items.add(file); this.files=dt.files; this.dispatchEvent(new Event('change',{bubbles:true})); return;} return orig.call(this);}; try{ b.click(); await sleep(1500); if(!done){const inp=[...document.querySelectorAll('input[type=file]')].pop(); if(inp){const dt=new DataTransfer(); dt.items.add(file); inp.files=dt.files; inp.dispatchEvent(new Event('change',{bubbles:true})); done=true;}} } finally{HTMLInputElement.prototype.click=orig;} return done?'ok':'not done';};
window.__clearIng=async()=>{ const ed=document.querySelector('[contenteditable=true]'); let p=ed; for(let i=0;i<6;i++) p=p.parentElement; const x=[...p.querySelectorAll('button')].find(b=>b.textContent.trim()=='close'&&b.getAttribute('aria-label')!='Add ingredients to the prompt box'); if(x){x.click(); await sleep(700);} return p.querySelectorAll('img').length; };
window.__addRef=async(w)=>{ const has=()=>[...document.querySelectorAll('input')].find(i=>i.placeholder&&i.placeholder.includes('Search')); if(!has()) __flowOpenPicker(); let inp=null; for(let t=0;t<10&&!inp;t++){await sleep(300); inp=has();} if(!inp) return false; const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; s.call(inp,w.replace(/\.jpg$/,'')); inp.dispatchEvent(new Event('input',{bubbles:true})); let o=null; for(let t=0;t<12&&!o;t++){await sleep(500); o=[...document.querySelectorAll('button[role=option]')].find(o=>o.textContent.trim().replace(/Image$/,'')==w);} if(!o) return false; o.click(); await sleep(1200); return true; };
window.__prep=async(refs,text)=>{ const c=await __clearIng(); const res=[]; for(const r of refs) res.push(await __addRef(r)); const ed=document.querySelector('[contenteditable=true]'); let p=ed; for(let i=0;i<6;i++) p=p.parentElement; const n=await __flowPrompt(text); return {cleared:c, refs:res, imgs:p.querySelectorAll('img').length, n}; };
window.__next=async()=>{ if(document.querySelector('[contenteditable=true]').textContent.length) return 'previous not submitted'; if(window.__v5i>=window.__v5.length) return 'DONE'; const j=window.__v5[window.__v5i]; const r=await __prep(j[0],j[1]); window.__v5i++; return (window.__v5i-1)+':'+JSON.stringify(r); };
'helpers ok';
